version: '2'
services:
  zookeeper:
    image: zookeeper:latest
    ports:
      - "2181:2181"
    volumes:
      - ./.zookeeper-data:/data
      - ./.zookeeper-datalog:/datalog
  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.33.10
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_MESSAGE_MAX_BYTES: 2000000
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
      LOG4J_LOGGER_KAFKA_AUTHORIZER_LOGGER: 'DEBUG, authorizerAppender'
      KAFKA_LOG_DIRS: '/kafka-log'
      KAFKA_HEAP_OPTS: '-Xms256m -Xmx256m'
    depends_on:
      - zookeeper
    volumes:
      - ./.kafka-log:/kafka-log
  kafka-manager:
    image: sheepkiller/kafka-manager:latest
    ports:
      - "9000:9000"
    depends_on:
      - kafka
    environment:
      ZK_HOSTS: zookeeper:2181
      APPLICATION_SECRET: letmein
      KM_ARGS: -Djava.net.preferIPv4Stack=true

